### PR TITLE
Remove file from queue only after the status has been updated

### PR DESCRIPTION
**Pull request by bdurrer**
This should solve issue #98

### CODE REVIEW

**Comment by SimonSimCity** [comment]
Thanks for this PR also.

Please elaborate how this would affect the other projects already depending on how it currently works and which backwards incompatible changes this would bring with it and how they could be taken down to the least risky change.

As far as I see (from looking at it quickly) it is sorely for updating the `StatusDetails` before updating the `Status`, am I right?

If yes, would it be possible for us to update the internal variables of both and then trigger a change of both of them? This would retain the old behavior but also have both variables ready when either of them triggers a change request.

Don't know how it sounds for you, but for me those two items (status and details about it) are strongly coupled together and maybe it's best to announce a change together - or after both variables are updated, right?

@large since you reported #98, I also want to hear your feedback here.

**Comment by SimonSimCity** [comment]
After again reading #98, would it be enough to just move the removing of the file from the queue in order to maximize the backwards compatibility? Please let me know how you think about it.

**Comment by bdurrer** [comment]
Moving the `RemoveFile` is the important part, yes.

Existing code would already have to deal with bundling of property-changes over both properties (which are not always raised in the same order), which would need to have detailed, implementation-specific tracking. That would be an crazy solution, which is deemed to break somewhen - like, now. 
If you implement something like that, you have to check the code on every update (unless you are a very brave [wo]man). This can be solved with a single sentence in the changelog.

Is it necessary? No. Is it sensible? Yes. 

Bundling the Status and StatusDetail update would probably be nice, but it would break existing `PropertyChanged` listeners for sure.

**Comment by SimonSimCity** [comment]
If you have time, could you have a look at an idea to streamline it? E.g. if we say that the status-details are always either updated on their own (if that at any time should be necessary) or before updating the status itself ...

I'd still consider it a breaking change, means we'd raise the version to 2.0.0, but I'd not wait since changes are not likely to happen soon.

If you don't have time, I'll take this up in the coming weeks, whenever I find some spare time 😅

**Comment by bdurrer** [comment]
It's currently absolutely no priority for me, as we currently only have a iOS and windows application, which are good enough in the current state. We might never release the android variant.

And privately I have other projects where I _should_ starte some PRs. 😁

**Comment by large** [comment]
Sorry for late reply @SimonSimCity ! :) Currently busy on other projects...

@bdurrer modification is correct. In my eyes it is not a break-change, just a small bugfix.
It is being standardized so the class handle it equal on every status (good catch on the pause also, btw).
When Status change, StatusDetails is always available before the IFile is removed from queue. That sound reasonable.

Also nuget packages are quite easy to downgrade if functionality is breaking, and a releasenote of changes is always correct to inform endusers 👍

That is my 2 cents.

PS: I had a hard time with Google to make them look into the issue with space / cancel also. Downloadmanager cursor isn't available during broadcast on downloadcomplete. Hopefully Android 9 will fix it.

**Comment by SimonSimCity** [comment]
Thanks very much for the feedback. I've looked through the implementation of the other platforms and found some other places on iOS and UWP, where the order or updating `Status` and `StatusDetails` was quite chaotic as well.

Streamlined it now. @large can you please verify that it now works as expected? If yes, I'll publish a new version on nuget soon.

**Comment by large** [comment]
@SimonSimCity I have tested your working example on a Android tablet and emulator using Android 9 SDK. Streamlined "Statusdetails" is a success! Works the most logical way, but I spotted another bug:

On some statuses you set: downloadFile.StatusDetails = **default(string);**
This results in downloadFile.StatusDetails beeing **null**, not an empty string as you would expect.

So the example crashed on this line:
System.Diagnostics.Debug.WriteLine("[Property changed] " + e.PropertyName + " -> " + sender.GetType().GetProperty(e.PropertyName).GetValue(sender, null).ToString());

I believe that your intention is to create an empty string, so my suggestion is to change all the default(string) to string.Empty so endusers don't need to check StatusDetails for null before using it.

If that isn't the case the the example needs to check for null before printing:
```
if (sender.GetType().GetProperty(e.PropertyName).GetValue(sender, null) != null)
    System.Diagnostics.Debug.WriteLine("[Property changed] " + e.PropertyName + " -> " + sender.GetType().GetProperty(e.PropertyName).GetValue(sender, null).ToString());
```

**Pull request merged**
